lsst/dax_apdb

- python/lsst/dax/apdb/apdbCassandra.py
- python/lsst/dax/apdb/apdbCassandraSchema.py
Cassandra does not store NULL so for realistic test we need non-NULL
payload for all table columns. I added new configuration option for
Cassandra backend which fills columns that are not explicitly set with
random data. I'm doing it the backend instead of ap_proto because it is
much simplere to do here and I need a quick and dirty way to do it right
now. For final implementation we won't need it ao it will be removed
when we settle on what final implementation is going to look like.
> DM-20580: Implement filling of empty fields with random data

- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/apdbSchema.py
This changes the config items to support environment variables rather
than using getPackageDir. This allows runtime evaluation of the
file path rather than config read evaluation (which then gets
written to quantum graph files). This allows graph building to
run on a different system to the system that executes that graph.
This is required for lsst/ap_association#119
> DM-30985: Change schema file discovery to use environment variables and expandvars

- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/apdbCassandra.py
- python/lsst/dax/apdb/apdbSql.py
- python/lsst/dax/apdb/apdbSqlSchema.py
- python/lsst/dax/apdb/tests/_apdb.py
- python/lsst/dax/apdb/tests/data_factory.py
- tests/test_apdbCassandra.py
- tests/test_apdbSql.py
Apdb interface was extended with few methods that will be needed for the
replication to/from PPDB. SQL implemention has these new methods working
but Cassandra implementation will be done on a separate ticket (it needs
schema extension and some experimenting). This new interface may still
change when the replication system implementation starts.
> DM-33313: Add methods to support future PPDB replication

- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/apdbCassandra.py
- python/lsst/dax/apdb/apdbCassandraSchema.py
- python/lsst/dax/apdb/apdbSchema.py
- python/lsst/dax/apdb/apdbSql.py
- python/lsst/dax/apdb/cassandra_utils.py
- python/lsst/dax/apdb/pixelization.py
- python/lsst/dax/apdb/tests/_apdb.py
- python/lsst/dax/apdb/tests/data_factory.py
- tests/test_apdbCassandra.py
APDB API added few methods to support replication to/from PPDB on a previous ticket. This update adds an implementation of these new methods to Cassandra backend. Cassandra code was updated to use execution profiles, as the previous model gets deprecated. Also a continuing refactoring of Cassandra implementation in a couple of commits. It makes sense to look at the final diff, some pieces were changed more than once.
> DM-33314: Implement missing methods for Cassandra backend

- mypy.ini
- python/lsst/dax/apdb/apdbSql.py
- python/lsst/dax/apdb/apdbSqlSchema.py
- tests/test_apdbSql.py
Adds a configuration field to ApdbSqlConfig which can specify alternative schema name to use for all tables. Schema needs to be created in advance, by default the default schema is used. Also adds a separate unit test case for Postgres (only runs if testing.postgres exists), which tests non-default schema name.
> DM-36497: Add support for specifying schema name for tables

- .github/workflows/formatting.yaml
- .pre-commit-config.yaml
- python/lsst/__init__.py
- python/lsst/dax/__init__.py
- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/apdbCassandra.py
- python/lsst/dax/apdb/apdbCassandraSchema.py
- python/lsst/dax/apdb/apdbSql.py
- python/lsst/dax/apdb/apdbSqlSchema.py
- python/lsst/dax/apdb/cassandra_utils.py
- python/lsst/dax/apdb/pixelization.py
- python/lsst/dax/apdb/tests/_apdb.py
- python/lsst/dax/apdb/timer.py
- tests/test_ap_verify_queries.py
- tests/test_apdbCassandra.py
- tests/test_apdbSql.py
- tests/test_apdbSqlSchema.py
This changes APDB interface for accessing history, history is now defined
in terms of "insert ID" values, each call to `store()` method generates
new "insert ID" in the database. APD interface is extended to query the
list of known insert IDs and drop them. Get-history methods now accept
a list of insert IDs.
This commit also includes changes for both backends to limit the columns
returned from "get" method to those declared in the schema, dropping
extra partitioning/clustering columns. This also simplifies unit tests.
> DM-36923: Re-design methods for export of APDB data.

- .pre-commit-config.yaml
- python/lsst/dax/apdb/apdbCassandra.py
- python/lsst/dax/apdb/apdbCassandraSchema.py
- python/lsst/dax/apdb/apdbSql.py
- python/lsst/dax/apdb/apdbSqlSchema.py
- python/lsst/dax/apdb/cassandra_utils.py
- tests/test_apdbCassandra.py
Major issue here was Pandas and our use of its to_sql method. Pandas is still not compatible with SA2 transaction handling. I added a terrible hack to woraround that, a Connection-like class which looks more like 1.4 Connection class and wraps actual Connection. All unit tests run successfully. Also lots of mypy fixes.
> DM-37744: Make SQL implementation compatible with sqlalchemy 2

- python/lsst/dax/apdb/apdbSql.py
Pandas 2.0 has a better support for sqlalchemy 2. The workaround that was needed for pandas 1 is no longer necessary and is conditionally disabled. When we migrate to pandas2 completely, that workaround can be removed.
This commit also fixes few mypy issues that appeared with new mypy version.
> Disable sqlalchemy 2 workaround for pandas 2 (DM-38553)

- python/lsst/dax/apdb/apdb.py
Changing it to `False`, `True` is only useful for production service and just wastes resources during testing.
> DM-40492: Change default value of use_insert_id

- pyproject.toml
- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/apdbCassandra.py
- python/lsst/dax/apdb/apdbCassandraSchema.py
- python/lsst/dax/apdb/apdbSchema.py
- python/lsst/dax/apdb/apdbSql.py
- python/lsst/dax/apdb/apdbSqlSchema.py
- python/lsst/dax/apdb/pixelization.py
- python/lsst/dax/apdb/tests/_apdb.py
- python/lsst/dax/apdb/tests/data_factory.py
- python/lsst/dax/apdb/timer.py
- tests/test_apdbCassandra.py
The ticket was for finding the best compaction options for Cassandra implementation, but that work has been postponed. The branch has a bunch of small improvements to the code - mypy, enabling foreign keys in sqlite. I'm going to merge this branch to avoid future conflicts with other development.
> DM-40819: Few improvements to dax_apdb code

- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/apdbCassandra.py
- python/lsst/dax/apdb/apdbSql.py
- python/lsst/dax/apdb/tests/_apdb.py
- tests/test_apdbCassandra.py
- tests/test_apdbSql.py
This PR adds two methods for querying the presence of a visit-detector on an APDB. The first, `Apdb.contains`, is the preferred long-term solution, but cannot be implemented without schema changes. The second, `ApdbSql.containsCcdVisit`, can work right away but requires arguments that are not compatible with `contains` (and cannot be _efficiently_ implemented in Cassandra).
The Jira issue(s) that would allow `containsCcdVisit` to be retired in favor of `contains` should be defined before this PR is merged.
> DM-41639: Allow Apdb queries for visit completion

- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- pyproject.toml
- python/lsst/dax/apdb/__init__.py
- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/apdbCassandra.py
- python/lsst/dax/apdb/apdbCassandraSchema.py
- python/lsst/dax/apdb/apdbMetadata.py
- python/lsst/dax/apdb/apdbMetadataCassandra.py
- python/lsst/dax/apdb/apdbMetadataSql.py
- python/lsst/dax/apdb/apdbSchema.py
- python/lsst/dax/apdb/apdbSql.py
- python/lsst/dax/apdb/apdbSqlSchema.py
- python/lsst/dax/apdb/cassandra_utils.py
- python/lsst/dax/apdb/tests/_apdb.py
- python/lsst/dax/apdb/versionTuple.py
- requirements.txt
- tests/config/schema.yaml
- tests/test_apdbCassandra.py
- tests/test_apdbSql.py
- tests/test_apdbSqlSchema.py
Apdb now understands `metadata` table specification in sdm_schemas. Apdb now verifies that its own version and schema version in sdm_schemas are compatible with the versions stored in metadata table. Both metadata table and sdm_schemas version numbers are optional, if they are missing they are assumed to be "0.1.0".
> DM-41028: Add schema version support and check to SQL backend

- .pre-commit-config.yaml
- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/apdbCassandra.py
- python/lsst/dax/apdb/apdbCassandraSchema.py
- python/lsst/dax/apdb/apdbConfigFreezer.py
- python/lsst/dax/apdb/apdbMetadataCassandra.py
- python/lsst/dax/apdb/apdbSchema.py
- python/lsst/dax/apdb/apdbSql.py
- python/lsst/dax/apdb/cassandra_utils.py
- python/lsst/dax/apdb/factory.py
- python/lsst/dax/apdb/tests/_apdb.py
- setup.cfg
- tests/test_apdbCassandra.py
- tests/test_apdbSql.py
Both implementations now store parts of configuration in metadata
table (if that table exists in the schema) and reload that configuration
when instantiated.
> DM-42489: Freeze APDB configuration in metadata table

- python/lsst/dax/apdb/tests/_apdb.py
The issue on this ticket has been fixed already (accidentally) on DM-42489, but there was no unit test for this problem. Extended one of the unit tests to cover it.
> DM-42798: Add a test for missing metadata table

- .github/workflows/build.yaml
- .pre-commit-config.yaml
- mypy.ini
- pyproject.toml
- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/apdbCassandra.py
- python/lsst/dax/apdb/apdbSql.py
- python/lsst/dax/apdb/tests/_apdb.py
- python/lsst/dax/apdb/tests/data_factory.py
- requirements.txt
- tests/test_ap_verify_queries.py
- tests/test_apdbCassandra.py
- ups/dax_apdb.table
This removes dependency on daf_base which should allow adding GA
for building and testing this package.
> DM-43509: Replace daf.base.DateTime with astropy Time

- .gitignore
- bin.src/SConscript
- bin.src/apdb-cli
- doc/lsst.dax.apdb/index.rst
- pyproject.toml
- python/lsst/dax/apdb/__init__.py
- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/apdbCassandra.py
- python/lsst/dax/apdb/apdbCassandraSchema.py
- python/lsst/dax/apdb/apdbIndex.py
- python/lsst/dax/apdb/apdbSql.py
- python/lsst/dax/apdb/cli/apdb_cli.py
- python/lsst/dax/apdb/cli/cli.py
- python/lsst/dax/apdb/cli/logging_cli.py
- python/lsst/dax/apdb/cli/options.py
- python/lsst/dax/apdb/factory.py
- python/lsst/dax/apdb/scripts/__init__.py
- python/lsst/dax/apdb/scripts/create_cassandra.py
- python/lsst/dax/apdb/scripts/create_sql.py
- python/lsst/dax/apdb/scripts/list_index.py
- python/lsst/dax/apdb/tests/_apdb.py
- requirements.txt
- tests/test_apdbCassandra.py
- tests/test_apdbSql.py
- tests/test_cli.py
- tests/test_index.py
- ups/dax_apdb.table
Two new methods `from_url` and `from_config` should be used for creating Apdb instances when a configuration file or configuration object exists. Other factory methods in `factory` module are for internal use only.
New `apdb-cli` script for now has a `create-sql` and `create-cassandra` subcommands which will replace `make_apdb` and its cousins. The commands take a bunch of options, create APDB instance, and write a new config file for it.
Add support for APDB index. Index is a configuration file which maps labels to the URIs of APDB configuration files. Apdb can be instantiated via `from_uri` method using `label:` prefix with the name of the label defined in the index file.
> DM-43414: Improve dax_apdb configuration and instantiation

- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cassandra/apdbCassandraReplica.py
- python/lsst/dax/apdb/cli/apdb_cli.py
- python/lsst/dax/apdb/cli/options.py
- python/lsst/dax/apdb/monitor.py
- python/lsst/dax/apdb/scripts/create_cassandra.py
- python/lsst/dax/apdb/scripts/create_sql.py
- python/lsst/dax/apdb/sql/apdbSql.py
- python/lsst/dax/apdb/sql/apdbSqlReplica.py
- python/lsst/dax/apdb/timer.py
- tests/test_monitor.py
New service can collect monitoring records (which is a collection of
tags and values) and publish them somewhere. For now publishing
to log stream is supported with records formatted as JSON objects.
Timer class is updated to publish timing info to monitoring service
in addition to logs.
> DM-43933: Add special service for collecting monitoring metrics

- doc/lsst.dax.apdb/index.rst
This PR brings the "Command line tools" section of the docs in line with [the module homepage topic type guidelines](https://developer.lsst.io/stack/module-homepage-topic-type.html#script-reference-section), including making the section linkable from other docs.
> DM-43416: Standardize module documentation

- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cassandra/apdbCassandraSchema.py
- python/lsst/dax/apdb/cli/apdb_cli.py
- python/lsst/dax/apdb/scripts/__init__.py
- python/lsst/dax/apdb/scripts/metadata.py
- python/lsst/dax/apdb/sql/apdbSql.py
- python/lsst/dax/apdb/sql/modelToSql.py
- python/lsst/dax/apdb/versionTuple.py
Short integer type was mapped to regular 4-byte integers (though we did not have short integers in the schema until 1.0.0). Short will now use SmallInteger for SQL and SMALLINT for Cassandra.
CLI command is added to dump/set/delete metadata table keys.
Also fixed version compatibility rules for minor version numbers.
> DM-44237: Fix short integer type mapping; add CLI for metadata access

- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/sql/apdbSql.py
- python/lsst/dax/apdb/tests/_apdb.py
- tests/test_apdbCassandra.py
Regular clients of Apdb interface do not need to know about versions, all version-related issues are handled internally. Removing to avoid accidental use of those methods.
> DM-44275: Remove version number access from Apdb interface

- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cassandra/apdbCassandraSchema.py
- python/lsst/dax/apdb/tests/_apdb.py
- tests/test_apdbCassandra.py
This implementation is inefficient as it does a full scan of the tables (which may also affect performace of other clients). If performance becomes an issue we may need to reimplement it using a separate dedicated table.
> DM-41671: Implement Apdb.containsVisitDetector for Cassandra

- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/sql/apdbSql.py
- python/lsst/dax/apdb/tests/_apdb.py
- python/lsst/dax/apdb/tests/data_factory.py
- tests/config/schema.yaml
- tests/test_apdbSqlSchema.py
DiaForcedSource table now defined ra/dec columns so that they can
be used to calculate partitioning index in Cassandra. DiaSource
table partitioning used a matching DiaObject partition index (and
spatial index in SQL). It is switched to always use DiaSource ra/dec
to make things uniform across all tables.
> DM-44619: Always use ra/dec columns for spatial indexing

- python/lsst/dax/apdb/cassandra/__init__.py
- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cassandra/apdbCassandraSchema.py
- python/lsst/dax/apdb/cli/options.py
- python/lsst/dax/apdb/scripts/create_cassandra.py
- requirements.txt
When creating a schema in an existing keyspace the code now will check its
replication factor and raise if it does not match requested one.
Also introduce a way to specify table options when creating tables.
`create-cassandra` CLI adds `--table-options` option pointing to a YAML file with
table options.
> DM-43623: Check replication factor for existing keyspaces

- .pre-commit-config.yaml
- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cli/apdb_cli.py
- python/lsst/dax/apdb/cli/logging_cli.py
- python/lsst/dax/apdb/scripts/delete_cassandra.py
- python/lsst/dax/apdb/scripts/list_cassandra.py
- tests/test_apdbCassandra.py
ApdbCassandra adds two class methods to list keyspaces in the cluster and delete keyspaces. Two CLI sub-commands also added that use these new methods.
> DM-44822: Add CLI commands to list and delete Cassandra instances

- python/lsst/dax/apdb/sql/apdbSql.py
This PR fixes a bug introduced in #61 that breaks SQLite APDBs (including those produced by unit tests). The bug only appears if the user has a DbAuth set up, which I assume is how it wasn't caught by Jenkins.
> Fix error with ApdbSql authentication with db-auth.yaml 

- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/tests/data_factory.py
Instead of sending None to insert queries, replace it with a special UNSET_VALUE which skips writing those values completely.
> DM-45233: Avoid storing tombstones in Cassandra

- doc/lsst.dax.apdb/index.rst
- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cli/apdb_cli.py
- python/lsst/dax/apdb/scripts/list_cassandra.py
- tests/test_apdbCassandra.py
Role names is the only useful info that I could extract from Cassandra
using CQL. It would be nice to have data size, but CQL does not have
that info.
Note that the role executing this command needs SELECT permissions
for `system_auth.role_permissions` table (have to be granted for every new role).
> DM-44902: Extend list-cassandra command to print role names

- python/lsst/dax/apdb/sql/apdbSql.py
- tests/test_apdbSql.py
SQLite by default creates an empty database when database file given in URL does not exist. It needs extra convincing with special URL syntax to not do that. When new APDB sqlite instance is created, its config file will have an updated URL with that extra syntax. When old config file is read which does not have that syntax, we modify URL and add the same options.
> DM-45683: Handle the case when sqlite database was removed

- .pre-commit-config.yaml
- python/lsst/dax/apdb/apdbSchema.py
- python/lsst/dax/apdb/sql/apdbSql.py
- python/lsst/dax/apdb/tests/_apdb.py
- python/lsst/dax/apdb/tests/data_factory.py
- tests/config/schema.yaml
- tests/test_apdbCassandra.py
- tests/test_apdbSql.py
- tests/test_apdbSqlSchema.py
Apdb could return naive or timezone-aware timestamps in DataFrames from queries depending on backend type. AP pipelines expect (and create new DataFrames) containing naive types. To keep things consistent, Apdb will now convert timezone-aware timestamp columns to naive. Unit test added to verify expected behavior.
> DM-45668: Convert timestamps to naive type on return from queries

- python/lsst/dax/apdb/apdbSchema.py
- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cassandra/cassandra_utils.py
- python/lsst/dax/apdb/sql/apdbSql.py
- python/lsst/dax/apdb/tests/_apdb.py
- python/lsst/dax/apdb/tests/data_factory.py
- requirements.txt
If Postgres server timezone is set to something then UTC we
need to add UTC timezone to input timestamps so that server
does not try to convert them to server timezone. I also added
check for input timestamps with timezones, and convert them
to UTC as well (this may not be necessary, just to be safe).
Improve timestamp handling for Cassandra, fixed truncation bug.
If input timestamps are aware then convert them to UTC and drop
timezone. Cassandra does not need timezone info if input is in UTC.
On return Cassandra makes naive time (in UTC), so no conversion is
necessary. There was a bug in converting timestamps to milliseconds
that dropped fractional part, this is now fixed.
> DM-45915: Fix handling of timezones for input timestamps.

- .pre-commit-config.yaml
- python/lsst/dax/apdb/schema_model.py
- python/lsst/dax/apdb/sql/apdbSql.py
SQLite complains when extra slashes appear at the start of URL,
but the error message is not quite comprehensible. To avoid triggering
that error the code now sanitizes URL before passing it to sqlalchemy.
> DM-46077: Add protection against extra slashes in sqlite URL

- pyproject.toml
This just adds the `apdb-cli` as a command line script to the project so that it is automatically installed when running `pip`.
> Add apdb-cli command line script to project config

- .pre-commit-config.yaml
- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cassandra/apdbCassandraSchema.py
- python/lsst/dax/apdb/cassandra/cassandra_utils.py
- python/lsst/dax/apdb/tests/_apdb.py
- python/lsst/dax/apdb/tests/data_factory.py
- tests/test_apdbCassandra.py
- tests/test_apdbSql.py
This patch adds one more internal table which tracks spatial partitions
for DiaObjects in the DiaObjectLast table. The code compares new
partitions with old and deletes records from DiaObjectLast which change
their partition before saving them.
> DM-45646: Improve handling of moving DiaObjects in Cassandra

- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cassandra/apdbCassandraSchema.py
- python/lsst/dax/apdb/cassandra/config.py
- python/lsst/dax/apdb/schema_model.py
ApdbCassandra configuration adds options to limit the number of rows in batch queries and the size of the batch queries. This includes fixing the error related to 64k limit of the batch queries for updates of DiaObjectLastToPartition table. There are still some batch queries that do not check the limits, but those are not likely to exceed Cassandra limits.
> DM-48391: Add options to limit the size of batch queries in Cassandra

- .pre-commit-config.yaml
- pyproject.toml
- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/sql/apdbSql.py
This fixes Postgres backend problem with np.float in the rendered query.
Cassandra handled that correctly, but I added a cast there as well, for
uniformity.
> DM-49135: Cast numpy.float type to float for sqlalchemy

- python/lsst/dax/apdb/apdb.py
- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/sql/apdbSql.py
- python/lsst/dax/apdb/tests/_apdb.py
Avoids full scan of of the source tables to determine if visit/detector are present. The method now requires region and time interval which enables use of partitioning key (but not full primary key).
> DM-49327: Improve performance of containsVisitDetector method

- .pre-commit-config.yaml
- python/lsst/dax/apdb/cli/options.py
- python/lsst/dax/apdb/sql/apdbSql.py
- python/lsst/dax/apdb/sql/modelToSql.py
Postgres backend rendered `sqlalchemy.Float` type as double precision,
resulting in all float columns to be 64-bit types. This patch switches
to `sqlalchemy.REAL` type instead. It increments patch for ApdbSql
version, migration script is implemented on the same branch.
> DM-49455: Fix float dataset type use in SQL backend

- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cassandra/apdbMetadataCassandra.py
- python/lsst/dax/apdb/sql/apdbMetadataSql.py
- python/lsst/dax/apdb/sql/apdbSql.py
- python/lsst/dax/apdb/tests/_apdb.py
- tests/test_ap_verify_queries.py
Previously the code assumed that a missing metadata table corresponds to the initial schema version 0.1.0. This caused issues in some cases, e.g. when schema name was missing or misspelled. With current state the metadata always exists in the schema, and this also allows us to simplify logic in few places.
> DM-49464: Assume that metadata table is always present

- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cassandra/apdbCassandraReplica.py
- python/lsst/dax/apdb/cassandra/apdbCassandraSchema.py
- python/lsst/dax/apdb/cassandra/cassandra_utils.py
- python/lsst/dax/apdb/cassandra/config.py
- python/lsst/dax/apdb/sql/apdbSql.py
- python/lsst/dax/apdb/sql/apdbSqlReplica.py
- python/lsst/dax/apdb/sql/apdbSqlSchema.py
- python/lsst/dax/apdb/tests/_apdb.py
- tests/test_apdbCassandra.py
This column is a part of the partitioning key and it is filled with
random numbers in reasonably narrow range. This aloows to distribute
writing of the chund data across many nodes in the cluster.
ApdbCassandraReplica version is updated to 1.1.0.
Verified to work OK with databases at 1.0.0 and 1.1.0.
> DM-50093: Add sub-chunk column to replica chunk tables

- .gitignore
- python/lsst/dax/apdb/apdbReplica.py
- python/lsst/dax/apdb/cassandra/apdbCassandraReplica.py
- python/lsst/dax/apdb/sql/apdbSql.py
- python/lsst/dax/apdb/sql/apdbSqlReplica.py
This PR adds a method to the `ApdbReplica` interface for accessing the database schema version. Implementation methods were added to the two concrete classes which implement this interface.
> DM-49202: Expose schema version in replication interface

- python/lsst/dax/apdb/cassandra/config.py
- python/lsst/dax/apdb/pixelization.py
Healpix does not support `maxRanges` in envelope(), which could potentially cause issues if region is too large. For APDB use case this should not be a problem as our regions are detector-size.
> DM-50796: Add support for healpix pixelization to Cassandra backend

- .github/workflows/mypy.yaml
- python/lsst/dax/apdb/cassandra/apdbCassandra.py
Avoids creating multi-partition BatchStatement by either grouping statements by partition or sending multiple statements concurrently.
> DM-50725: Switch to single-partition batches writes for Cassandra APDB

- python/lsst/dax/apdb/cassandra/apdbCassandra.py
- python/lsst/dax/apdb/cassandra/apdbCassandraAdmin.py
- python/lsst/dax/apdb/cassandra/apdbCassandraSchema.py
- python/lsst/dax/apdb/cassandra/config.py
- python/lsst/dax/apdb/cassandra/connectionContext.py
- python/lsst/dax/apdb/cassandra/partitioner.py
- python/lsst/dax/apdb/cli/apdb_cli.py
- python/lsst/dax/apdb/scripts/__init__.py
- python/lsst/dax/apdb/scripts/partition.py
- python/lsst/dax/apdb/tests/_apdb.py
- python/lsst/dax/apdb/tests/_apdb_admin.py
- python/lsst/dax/apdb/tests/cassandra_mixin.py
- python/lsst/dax/apdb/tests/utils.py
- tests/test_apdbCassandra.py
- tests/test_apdbCassandraAdmin.py
- tests/test_apdbSql.py
- tests/test_cassandraPartitioner.py
Added new CLI tools to extend/shrink range of time partitions for time-partitioned tables.
This changes patch-level version of ApdbCassandra class. There is no actual schema change, the only difference is we now store current time partition range in metadata table.
> DM-51824: Implement management of per-partition tables in APDB

- python/lsst/dax/apdb/apdbSchema.py
- python/lsst/dax/apdb/cassandra/apdbCassandraSchema.py
- python/lsst/dax/apdb/sql/apdbSqlSchema.py
- python/lsst/dax/apdb/tests/_apdb.py
- tests/config/schema.yaml
- tests/test_apdbSqlSchema.py
Apdb.tableDef() now works for SSSource table as well. The table still does not exis in database schema, it may be added later.
> DM-52233: Provide access to SSSource table schema
